// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBjqvUiieEhDB5NvSauqkYw-xwT3DzAA3U',
    appId: '1:841966210722:web:08a2b7a2b4ea2cbf44d1fb',
    messagingSenderId: '841966210722',
    projectId: 'movie-labbc',
    authDomain: 'movie-labbc.firebaseapp.com',
    storageBucket: 'movie-labbc.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBnAg_CDavHeKnVfkj63f3A-ZMt3tHDFO0',
    appId: '1:841966210722:android:b2c04ab36d5d5fd544d1fb',
    messagingSenderId: '841966210722',
    projectId: 'movie-labbc',
    storageBucket: 'movie-labbc.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCtJoJdhsDPb4SKGb60KEC12dazRQIFekA',
    appId: '1:841966210722:ios:fb35be4600dbc87e44d1fb',
    messagingSenderId: '841966210722',
    projectId: 'movie-labbc',
    storageBucket: 'movie-labbc.firebasestorage.app',
    iosBundleId: 'com.majdmakhoul.movieMatcher',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCtJoJdhsDPb4SKGb60KEC12dazRQIFekA',
    appId: '1:841966210722:ios:6ae03fe986daf6ce44d1fb',
    messagingSenderId: '841966210722',
    projectId: 'movie-labbc',
    storageBucket: 'movie-labbc.firebasestorage.app',
    iosBundleId: 'com.example.movieMatcher',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBjqvUiieEhDB5NvSauqkYw-xwT3DzAA3U',
    appId: '1:841966210722:web:e78ebf3a7941fd3c44d1fb',
    messagingSenderId: '841966210722',
    projectId: 'movie-labbc',
    authDomain: 'movie-labbc.firebaseapp.com',
    storageBucket: 'movie-labbc.firebasestorage.app',
  );
}
